#!/usr/bin/env bash

# Run Stack test on the given directory, setting up the Nix
# integration with Nixpkgs controlled by sources.nix

# Should be run from top-level directory in repo:
#
# ci/stack-test theta

# Slightly fiddly way to get the path to the version of Nixpkgs pinned
# by the top-level Theta Flake
function get_metadata {
    eval echo "$(nix flake metadata $1 --json | jq $2)"
}
nixpkgs_rev=$(get_metadata . .locks.nodes.nixpkgs.locked.rev)
nixpkgs_path=$(get_metadata "github:NixOS/nixpkgs/$nixpkgs_rev" .path)

cd $1
stack --nix \
      --nix-shell-file stack-shell.nix \
      --nix-path="nixpkgs=$nixpkgs_path" \
      test
